name: Build
on: 
  push:
    branches: [ master ]
    paths-ignore:
    - '.github/workflows/tag.yml'
  workflow_run:
    workflows: ["Tag"]
    types:
      - completed
  workflow_dispatch:
concurrency:
  group: ${{ github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - name: cache yarn modules
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: cache gatsby cache
        uses: pat-s/always-upload-cache@v2.1.5
        with:
          path: .cache
          key: ${{ runner.os }}-gatsby-cache-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-gatsby-cache-
      - name: cache gatsby public
        uses: pat-s/always-upload-cache@v2.1.5
        with:
          path: public
          key: ${{ runner.os }}-gatsby-public-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-gatsby-public-
      - name: cache gatsby public-cache
        uses: pat-s/always-upload-cache@v2.1.5
        with:
          path: public-cache
          key: ${{ runner.os }}-gatsby-public-cache-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-gatsby-public-cache-
      - name: Restore cache
        run: node gh-pages-cache-restore.js
      - name: Install and Build 🔧 # This example project is built using yarn and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          yarn install --immutable
          yarn build
          echo "modules.lsposed.org" > ./public/CNAME
        env:
          GRAPHQL_TOKEN: ${{ secrets.GRAPHQL_TOKEN }}
          GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
      - name: clean up caches on failure
        if: ${{ failure() || cancelled() }}
        run: |
          rm -rf public/*
          rm -rf public-cache/*
          rm -rf .cache/*
      - name: Refresh cache
        run: node gh-pages-cache.js
      - uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: public # The folder the action should deploy.
          git-config-name: "null"
          git-config-email: "null"
          single-commit: true
